//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ReceivingOrderDetail
    {
        public string ReceiveNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
        public Nullable<double> ReceiveUnitQty { get; set; }
        public string RecapNumber { get; set; }
    
        public virtual Tbl_TRS_ReceivingOrder Tbl_TRS_ReceivingOrder { get; set; }
    }
}
