//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ACC_CustomerInvoiceReceivable
    {
        public string InvoiceNumber { get; set; }
        public string TaxNumber { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<System.DateTime> PaymentSchedule { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_ACC_CustomerInvoice Tbl_ACC_CustomerInvoice { get; set; }
    }
}
