//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_QC_InspectionIncoming
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_QC_InspectionIncoming()
        {
            this.Tbl_QC_InspectionIncomingDefects = new HashSet<Tbl_QC_InspectionIncomingDefects>();
        }
    
        public string InspectionNumber { get; set; }
        public string InspectionGate { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> TotalCheck { get; set; }
        public Nullable<double> TotalDefectUnit { get; set; }
        public Nullable<double> TotalDefectQty { get; set; }
        public Nullable<double> Replaced { get; set; }
        public Nullable<double> Remains { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_InspectionGate Tbl_MST_InspectionGate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_QC_InspectionIncomingDefects> Tbl_QC_InspectionIncomingDefects { get; set; }
        public virtual Tbl_MST_PartIdentificationSupplier Tbl_MST_PartIdentificationSupplier { get; set; }
    }
}
