//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_MasterListKanbanProduction
    {
        public string OrderNumber { get; set; }
        public string LineId { get; set; }
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> N1 { get; set; }
        public Nullable<double> N2 { get; set; }
        public Nullable<double> N3 { get; set; }
        public Nullable<double> QtyByDay { get; set; }
        public Nullable<double> QtyByShift { get; set; }
        public Nullable<double> QtyByHour { get; set; }
        public Nullable<double> KanbanCalc1 { get; set; }
        public Nullable<double> KanbanCalc2 { get; set; }
        public Nullable<double> KanbanCalc3 { get; set; }
        public Nullable<double> KanbanCalc4 { get; set; }
        public Nullable<double> KanbanCalc5 { get; set; }
        public Nullable<double> KanbanN10 { get; set; }
        public Nullable<double> KanbanN00 { get; set; }
        public Nullable<double> KanbanN01 { get; set; }
        public Nullable<double> MinStock { get; set; }
        public Nullable<double> MaxStock { get; set; }
    
        public virtual Tbl_TRS_ControlPlanning Tbl_TRS_ControlPlanning { get; set; }
    }
}
