//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_SupplierCostCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_SupplierCostCenter()
        {
            this.Tbl_MST_PartRawMaterialsCostCenter = new HashSet<Tbl_MST_PartRawMaterialsCostCenter>();
        }
    
        public string SupplierId { get; set; }
        public string CostId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string CostName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartRawMaterialsCostCenter> Tbl_MST_PartRawMaterialsCostCenter { get; set; }
        public virtual Tbl_MST_Supplier Tbl_MST_Supplier { get; set; }
    }
}
