//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_KanbanCalculation
    {
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> InProcess { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<double> PrepareHeijunka { get; set; }
        public Nullable<double> WIP { get; set; }
        public Nullable<double> PrepareDelivery { get; set; }
        public string LineId { get; set; }
    
        public virtual Tbl_MST_Line Tbl_MST_Line { get; set; }
    }
}
