//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TMS_WorkingShiftHour
    {
        public string GroupId { get; set; }
        public string ShiftId { get; set; }
        public string DayId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_TMS_WorkingDay Tbl_TMS_WorkingDay { get; set; }
        public virtual Tbl_TMS_WorkingShiftMaster Tbl_TMS_WorkingShiftMaster { get; set; }
    }
}
