//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_KanbanSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_KanbanSetting()
        {
            this.Tbl_MST_KanbanSettingSequence = new HashSet<Tbl_MST_KanbanSettingSequence>();
        }
    
        public string CustomerId { get; set; }
        public Nullable<bool> SalesOrder { get; set; }
        public Nullable<bool> Production { get; set; }
        public Nullable<bool> DeliveryOrder { get; set; }
        public string DataSparator { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_KanbanSettingSequence> Tbl_MST_KanbanSettingSequence { get; set; }
    }
}
