//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ForecastOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_ForecastOrder()
        {
            this.Tbl_TRS_ForecastOrderApproval = new HashSet<Tbl_TRS_ForecastOrderApproval>();
            this.Tbl_TRS_ForecastOrderRevision = new HashSet<Tbl_TRS_ForecastOrderRevision>();
            this.Tbl_TRS_MasterListKanbanSupplier = new HashSet<Tbl_TRS_MasterListKanbanSupplier>();
            this.Tbl_TRS_ForecastOrderDetail = new HashSet<Tbl_TRS_ForecastOrderDetail>();
        }
    
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderYear { get; set; }
        public string OrderMonth { get; set; }
        public string SupplierId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> Shift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ForecastOrderApproval> Tbl_TRS_ForecastOrderApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ForecastOrderRevision> Tbl_TRS_ForecastOrderRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_MasterListKanbanSupplier> Tbl_TRS_MasterListKanbanSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ForecastOrderDetail> Tbl_TRS_ForecastOrderDetail { get; set; }
    }
}
