//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_MeasurementsCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_MeasurementsCategories()
        {
            this.Tbl_MST_PartFinishGoods = new HashSet<Tbl_MST_PartFinishGoods>();
            this.Tbl_MST_PartRawMaterials = new HashSet<Tbl_MST_PartRawMaterials>();
            this.Tbl_MST_PartProductionMaterials = new HashSet<Tbl_MST_PartProductionMaterials>();
        }
    
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Remarks { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartFinishGoods> Tbl_MST_PartFinishGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartRawMaterials> Tbl_MST_PartRawMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartProductionMaterials> Tbl_MST_PartProductionMaterials { get; set; }
    }
}
