//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ACC_InvoiceRecap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ACC_InvoiceRecap()
        {
            this.Tbl_ACC_InvoiceRecapApproval = new HashSet<Tbl_ACC_InvoiceRecapApproval>();
            this.Tbl_ACC_InvoiceRecapDetail = new HashSet<Tbl_ACC_InvoiceRecapDetail>();
        }
    
        public string RecapNumber { get; set; }
        public Nullable<System.DateTime> RecapDate { get; set; }
        public string RecapYear { get; set; }
        public string RecapMonth { get; set; }
        public string ReceiveNote { get; set; }
        public string InvoiceNumber { get; set; }
        public string TaxInvoice { get; set; }
        public string SupplierId { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> PPN { get; set; }
        public Nullable<double> PPH23 { get; set; }
        public Nullable<double> DebitNote { get; set; }
        public Nullable<double> Payment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> ReceiveStartDate { get; set; }
        public Nullable<System.DateTime> ReceiveEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ACC_InvoiceRecapApproval> Tbl_ACC_InvoiceRecapApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ACC_InvoiceRecapDetail> Tbl_ACC_InvoiceRecapDetail { get; set; }
    }
}
