//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ControlPlanning
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_ControlPlanning()
        {
            this.Tbl_TRS_ControlPlanningApproval = new HashSet<Tbl_TRS_ControlPlanningApproval>();
            this.Tbl_TRS_ControlPlanningDetail = new HashSet<Tbl_TRS_ControlPlanningDetail>();
            this.Tbl_TRS_ControlPlanningRevision = new HashSet<Tbl_TRS_ControlPlanningRevision>();
            this.Tbl_TRS_MasterListKanbanProduction = new HashSet<Tbl_TRS_MasterListKanbanProduction>();
        }
    
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderYear { get; set; }
        public string OrderMonth { get; set; }
        public string LineId { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> StartDateProduction { get; set; }
        public Nullable<System.DateTime> EndDateProduction { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ControlPlanningApproval> Tbl_TRS_ControlPlanningApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ControlPlanningDetail> Tbl_TRS_ControlPlanningDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ControlPlanningRevision> Tbl_TRS_ControlPlanningRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_MasterListKanbanProduction> Tbl_TRS_MasterListKanbanProduction { get; set; }
    }
}
