//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TMS_WorkingShiftPatternMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TMS_WorkingShiftPatternMaster()
        {
            this.Tbl_TMS_WorkingShiftSchedule = new HashSet<Tbl_TMS_WorkingShiftSchedule>();
        }
    
        public string GroupId { get; set; }
        public int PatternNumber { get; set; }
        public string ShiftId { get; set; }
        public Nullable<int> TotalDay { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_TMS_WorkingShiftPatternGroup Tbl_TMS_WorkingShiftPatternGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TMS_WorkingShiftSchedule> Tbl_TMS_WorkingShiftSchedule { get; set; }
    }
}
