//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_Customer()
        {
            this.Tbl_MST_CustomerContact = new HashSet<Tbl_MST_CustomerContact>();
            this.Tbl_MST_PartFinishGoods = new HashSet<Tbl_MST_PartFinishGoods>();
            this.Tbl_TRS_SalesOrder = new HashSet<Tbl_TRS_SalesOrder>();
            this.Tbl_TRS_DeliveryOrder = new HashSet<Tbl_TRS_DeliveryOrder>();
        }
    
        public string CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string AccountCode { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Provience { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Websites { get; set; }
        public string TaxId { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_CustomerContact> Tbl_MST_CustomerContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartFinishGoods> Tbl_MST_PartFinishGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_SalesOrder> Tbl_TRS_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_DeliveryOrder> Tbl_TRS_DeliveryOrder { get; set; }
    }
}
