//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_StockRawReturn
    {
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> MinStock { get; set; }
        public Nullable<double> MaxStock { get; set; }
        public Nullable<double> StockQty { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Tbl_MST_PartRawMaterials Tbl_MST_PartRawMaterials { get; set; }
    }
}
