//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_SupplierOrderKanban
    {
        public string KanbanKey { get; set; }
        public Nullable<double> KanbanRun { get; set; }
        public string OrderNumber { get; set; }
        public string ReceiveNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string Unit { get; set; }
        public string KanbanCycle { get; set; }
        public Nullable<System.DateTime> IncomingDate { get; set; }
        public Nullable<System.DateTime> IncomingTime { get; set; }
        public Nullable<bool> Received { get; set; }
        public string CostId { get; set; }
    
        public virtual Tbl_TRS_SupplierOrderDetail Tbl_TRS_SupplierOrderDetail { get; set; }
    }
}
