//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_DefectList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_DefectList()
        {
            this.Tbl_QC_InspectionDefects = new HashSet<Tbl_QC_InspectionDefects>();
            this.Tbl_QC_InspectionIncomingDefects = new HashSet<Tbl_QC_InspectionIncomingDefects>();
        }
    
        public string DefectId { get; set; }
        public string DefectName { get; set; }
        public string DefectCategory { get; set; }
        public string PartCategory { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_DefectCategory Tbl_MST_DefectCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_QC_InspectionDefects> Tbl_QC_InspectionDefects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_QC_InspectionIncomingDefects> Tbl_QC_InspectionIncomingDefects { get; set; }
    }
}
