//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_RequestOrderPartsDetail
    {
        public string OrderNumber { get; set; }
        public string LineId { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> StockKanban { get; set; }
        public Nullable<double> StockQty { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> OrderUnitQty { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
    
        public virtual Tbl_TRS_RequestOrderParts Tbl_TRS_RequestOrderParts { get; set; }
    }
}
