//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_QC_InspectionIncomingDefects
    {
        public string InspectionNumber { get; set; }
        public string DefectNumber { get; set; }
        public string DefectId { get; set; }
        public Nullable<double> DefectQty { get; set; }
        public Nullable<bool> PartReturn { get; set; }
        public Nullable<bool> Repair { get; set; }
        public Nullable<bool> Scrap { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_DefectList Tbl_MST_DefectList { get; set; }
        public virtual Tbl_QC_InspectionIncoming Tbl_QC_InspectionIncoming { get; set; }
    }
}
