//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TMS_WorkingShiftMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TMS_WorkingShiftMaster()
        {
            this.Tbl_TMS_WorkingShiftHour = new HashSet<Tbl_TMS_WorkingShiftHour>();
        }
    
        public string GroupId { get; set; }
        public string ShiftId { get; set; }
        public string ShiftName { get; set; }
        public Nullable<bool> DayType { get; set; }
        public Nullable<int> Sort { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_TMS_WorkingDayType Tbl_TMS_WorkingDayType { get; set; }
        public virtual Tbl_TMS_WorkingShiftGroup Tbl_TMS_WorkingShiftGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TMS_WorkingShiftHour> Tbl_TMS_WorkingShiftHour { get; set; }
    }
}
