//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ReceivingOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_ReceivingOrder()
        {
            this.Tbl_TRS_ReceivingOrderDetailKanban = new HashSet<Tbl_TRS_ReceivingOrderDetailKanban>();
            this.Tbl_TRS_ReceivingOrderDetail = new HashSet<Tbl_TRS_ReceivingOrderDetail>();
        }
    
        public string ReceiveNumber { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string OrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> ReturnPart { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_TRS_SupplierOrder Tbl_TRS_SupplierOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ReceivingOrderDetailKanban> Tbl_TRS_ReceivingOrderDetailKanban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ReceivingOrderDetail> Tbl_TRS_ReceivingOrderDetail { get; set; }
    }
}
