//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_StockTaking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_StockTaking()
        {
            this.Tbl_TRS_StockTakingApproval = new HashSet<Tbl_TRS_StockTakingApproval>();
            this.Tbl_TRS_StockTakingDetail = new HashSet<Tbl_TRS_StockTakingDetail>();
        }
    
        public string InventoryNumber { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public Nullable<System.DateTime> InventoryStartTime { get; set; }
        public Nullable<System.DateTime> InventoryEndTime { get; set; }
        public string StockType { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Updated { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_StockTakingApproval> Tbl_TRS_StockTakingApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_StockTakingDetail> Tbl_TRS_StockTakingDetail { get; set; }
    }
}
