//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_MasterListKanbanSupplier
    {
        public string OrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> QtyByKanban { get; set; }
        public Nullable<double> QtyByDay { get; set; }
        public Nullable<double> KanbanN10 { get; set; }
        public Nullable<double> KanbanN00 { get; set; }
        public Nullable<double> KanbanN01 { get; set; }
        public Nullable<double> KanbanReg { get; set; }
        public Nullable<double> SafetyHour { get; set; }
        public Nullable<double> SafetyKanban { get; set; }
        public Nullable<double> SafetyParts { get; set; }
        public Nullable<double> WorkHour { get; set; }
        public Nullable<double> Cycle1 { get; set; }
        public Nullable<double> Cycle2 { get; set; }
        public Nullable<double> Cycle3 { get; set; }
        public Nullable<double> MinStock { get; set; }
        public Nullable<double> MaxStock { get; set; }
    
        public virtual Tbl_TRS_ForecastOrder Tbl_TRS_ForecastOrder { get; set; }
    }
}
