//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_DeliveryOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_DeliveryOrder()
        {
            this.Tbl_TRS_DeliveryOrderDetail = new HashSet<Tbl_TRS_DeliveryOrderDetail>();
        }
    
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string CustomerId { get; set; }
        public string SONumber { get; set; }
        public string RefNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> KanbanOrder { get; set; }
        public string KanbanUsage { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_Customer Tbl_MST_Customer { get; set; }
        public virtual Tbl_TRS_SalesOrder Tbl_TRS_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_DeliveryOrderDetail> Tbl_TRS_DeliveryOrderDetail { get; set; }
    }
}
