//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ReturnPartDetail
    {
        public string ReturnNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> ReturnUnitQty { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
    
        public virtual Tbl_MST_PartRawMaterials Tbl_MST_PartRawMaterials { get; set; }
        public virtual Tbl_TRS_ReturnPart Tbl_TRS_ReturnPart { get; set; }
    }
}
