//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TMS_WorkingCalendarDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TMS_WorkingCalendarDay()
        {
            this.Tbl_TMS_WorkingCalendar = new HashSet<Tbl_TMS_WorkingCalendar>();
        }
    
        public string DayId { get; set; }
        public string DayName { get; set; }
        public Nullable<bool> Holidays { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TMS_WorkingCalendar> Tbl_TMS_WorkingCalendar { get; set; }
    }
}
