//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_KanbanSettingSequence
    {
        public string CustomerId { get; set; }
        public double SequenceNumber { get; set; }
        public string FieldName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remark { get; set; }
    
        public virtual Tbl_MST_KanbanSetting Tbl_MST_KanbanSetting { get; set; }
    }
}
