//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_Bank()
        {
            this.Tbl_MST_SupplierBankAccount = new HashSet<Tbl_MST_SupplierBankAccount>();
            this.Tbl_MST_AccountingBankAccount = new HashSet<Tbl_MST_AccountingBankAccount>();
        }
    
        public string BankId { get; set; }
        public string BankName { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> TransferFee { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_SupplierBankAccount> Tbl_MST_SupplierBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_AccountingBankAccount> Tbl_MST_AccountingBankAccount { get; set; }
    }
}
