//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ACC_InvoiceRecapApproval
    {
        public string RecapNumber { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ApprovalLevel { get; set; }
        public string ApprovalName { get; set; }
        public string ApprovalEmail { get; set; }
        public Nullable<bool> SentEmail { get; set; }
        public Nullable<System.DateTime> SentEmailDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual Tbl_ACC_InvoiceRecap Tbl_ACC_InvoiceRecap { get; set; }
    }
}
