//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_StockAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_StockAdjustment()
        {
            this.Tbl_TRS_StockAdjustmentApproval = new HashSet<Tbl_TRS_StockAdjustmentApproval>();
            this.Tbl_TRS_StockAdjustmentDetail = new HashSet<Tbl_TRS_StockAdjustmentDetail>();
        }
    
        public string AdjustmentNumber { get; set; }
        public Nullable<System.DateTime> AdjustmentDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string AreaId { get; set; }
        public string LocationId { get; set; }
        public string InventoryNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_StockAdjustmentApproval> Tbl_TRS_StockAdjustmentApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_StockAdjustmentDetail> Tbl_TRS_StockAdjustmentDetail { get; set; }
    }
}
