//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_SupplierOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_SupplierOrderDetail()
        {
            this.Tbl_TRS_SupplierOrderKanban = new HashSet<Tbl_TRS_SupplierOrderKanban>();
        }
    
        public string OrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
        public Nullable<double> MaxStock { get; set; }
        public Nullable<double> StockKanban { get; set; }
        public Nullable<double> OrderUnitQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_SupplierOrderKanban> Tbl_TRS_SupplierOrderKanban { get; set; }
        public virtual Tbl_TRS_SupplierOrder Tbl_TRS_SupplierOrder { get; set; }
    }
}
