//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_PartBillOfMaterials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_PartBillOfMaterials()
        {
            this.Tbl_MST_PartBillOfMaterialsDetails = new HashSet<Tbl_MST_PartBillOfMaterialsDetails>();
        }
    
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public string LineId { get; set; }
        public string Revision { get; set; }
        public string Remarks { get; set; }
        public string ImagesLocation { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_Line Tbl_MST_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartBillOfMaterialsDetails> Tbl_MST_PartBillOfMaterialsDetails { get; set; }
    }
}
