//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ForecastOrderRevision
    {
        public string OrderNumber { get; set; }
        public int RevisionNumber { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public string RevisionBy { get; set; }
        public string Description { get; set; }
    
        public virtual Tbl_TRS_ForecastOrder Tbl_TRS_ForecastOrder { get; set; }
    }
}
