//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ControlPlanningDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_ControlPlanningDetail()
        {
            this.Tbl_TRS_ScheduleProduction = new HashSet<Tbl_TRS_ScheduleProduction>();
        }
    
        public string OrderNumber { get; set; }
        public string LineId { get; set; }
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> N1 { get; set; }
        public Nullable<double> N2 { get; set; }
        public Nullable<double> N3 { get; set; }
        public Nullable<double> DailyQty { get; set; }
        public Nullable<double> ShiftQty { get; set; }
        public string SONumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ScheduleProduction> Tbl_TRS_ScheduleProduction { get; set; }
        public virtual Tbl_TRS_ControlPlanning Tbl_TRS_ControlPlanning { get; set; }
    }
}
