//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_CustomerContact
    {
        public string CustomerId { get; set; }
        public string ContactName { get; set; }
        public string Organization { get; set; }
        public string Position { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<bool> ReceiveOrder { get; set; }
    
        public virtual Tbl_MST_Customer Tbl_MST_Customer { get; set; }
    }
}
