//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ScheduleProduction
    {
        public string OrderNumber { get; set; }
        public string LineId { get; set; }
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public string ShiftId { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<double> ProductionQty { get; set; }
    
        public virtual Tbl_TRS_ControlPlanningDetail Tbl_TRS_ControlPlanningDetail { get; set; }
    }
}
