//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_PartBillOfMaterialsDetails
    {
        public string CustomerId { get; set; }
        public string PartNumberParent { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> PartType { get; set; }
        public string Revision { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Remarks { get; set; }
        public string LineId { get; set; }
        public Nullable<bool> Passthrough { get; set; }
    
        public virtual Tbl_MST_PartType Tbl_MST_PartType { get; set; }
        public virtual Tbl_MST_PartBillOfMaterials Tbl_MST_PartBillOfMaterials { get; set; }
    }
}
