//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_InspectionGate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_InspectionGate()
        {
            this.Tbl_QC_Inspection = new HashSet<Tbl_QC_Inspection>();
            this.Tbl_QC_InspectionIncoming = new HashSet<Tbl_QC_InspectionIncoming>();
            this.Tbl_QC_ProblemInformation = new HashSet<Tbl_QC_ProblemInformation>();
        }
    
        public string GateId { get; set; }
        public string GateName { get; set; }
        public string InspectionType { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_QC_Inspection> Tbl_QC_Inspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_QC_InspectionIncoming> Tbl_QC_InspectionIncoming { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_QC_ProblemInformation> Tbl_QC_ProblemInformation { get; set; }
    }
}
