//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_PartRawMaterialsCostCenter
    {
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CostId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string ClassificationId { get; set; }
        public string PaymentId { get; set; }
        public string CategoryId { get; set; }
    
        public virtual Tbl_MST_SupplierCostCenter Tbl_MST_SupplierCostCenter { get; set; }
        public virtual Tbl_MST_AccountingCategory Tbl_MST_AccountingCategory { get; set; }
        public virtual Tbl_MST_AccountingClassification Tbl_MST_AccountingClassification { get; set; }
        public virtual Tbl_MST_AccountingPayment Tbl_MST_AccountingPayment { get; set; }
        public virtual Tbl_MST_PartRawMaterials Tbl_MST_PartRawMaterials { get; set; }
    }
}
