//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_StockTakingDetail
    {
        public string InventoryNumber { get; set; }
        public string CustomerId { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> StockKanban { get; set; }
        public Nullable<double> StockQty { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BalanceQty { get; set; }
        public string LineId { get; set; }
    
        public virtual Tbl_TRS_StockTaking Tbl_TRS_StockTaking { get; set; }
    }
}
