//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_Line()
        {
            this.Tbl_MST_KanbanCalculation = new HashSet<Tbl_MST_KanbanCalculation>();
            this.Tbl_MST_PartProductionMaterials = new HashSet<Tbl_MST_PartProductionMaterials>();
            this.Tbl_MST_KanbanProduction = new HashSet<Tbl_MST_KanbanProduction>();
            this.Tbl_MST_PartBillOfMaterials = new HashSet<Tbl_MST_PartBillOfMaterials>();
            this.Tbl_MST_LineGate = new HashSet<Tbl_MST_LineGate>();
        }
    
        public string LineId { get; set; }
        public string LineName { get; set; }
        public int GroupId { get; set; }
        public string AreaId { get; set; }
        public string LocationId { get; set; }
        public string KanbanCode { get; set; }
        public string KanbanColor { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_Color Tbl_MST_Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_KanbanCalculation> Tbl_MST_KanbanCalculation { get; set; }
        public virtual Tbl_MST_LineGroup Tbl_MST_LineGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartProductionMaterials> Tbl_MST_PartProductionMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_KanbanProduction> Tbl_MST_KanbanProduction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartBillOfMaterials> Tbl_MST_PartBillOfMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_LineGate> Tbl_MST_LineGate { get; set; }
    }
}
