//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_KanbanCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_KanbanCycle()
        {
            this.Tbl_MST_KanbanCycleTime = new HashSet<Tbl_MST_KanbanCycleTime>();
        }
    
        public string SupplierId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Cycle1 { get; set; }
        public Nullable<double> Cycle2 { get; set; }
        public Nullable<double> Cycle3 { get; set; }
        public string CycleTime { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_Supplier Tbl_MST_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_KanbanCycleTime> Tbl_MST_KanbanCycleTime { get; set; }
    }
}
