//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_PartFinishGoods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_PartFinishGoods()
        {
            this.Tbl_MST_PartFinishGoodsPrice = new HashSet<Tbl_MST_PartFinishGoodsPrice>();
            this.Tbl_MST_PartFinishGoodsRelation = new HashSet<Tbl_MST_PartFinishGoodsRelation>();
            this.Tbl_TRS_SalesOrderDetail = new HashSet<Tbl_TRS_SalesOrderDetail>();
            this.Tbl_TRS_DeliveryOrderDetail = new HashSet<Tbl_TRS_DeliveryOrderDetail>();
            this.Tbl_MST_KanbanProduction = new HashSet<Tbl_MST_KanbanProduction>();
        }
    
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public string PartNumberCustomer { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public string CustomerUnitModel { get; set; }
        public string CategoryId { get; set; }
        public string AreaId { get; set; }
        public string LocationId { get; set; }
        public string UnitLevel1 { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public Nullable<bool> PassThrough { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string PackingId { get; set; }
    
        public virtual Tbl_MST_MeasurementsCategories Tbl_MST_MeasurementsCategories { get; set; }
        public virtual Tbl_MST_MeasurementsUnits Tbl_MST_MeasurementsUnits { get; set; }
        public virtual Tbl_MST_WarehouseArea Tbl_MST_WarehouseArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartFinishGoodsPrice> Tbl_MST_PartFinishGoodsPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartFinishGoodsRelation> Tbl_MST_PartFinishGoodsRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_SalesOrderDetail> Tbl_TRS_SalesOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_DeliveryOrderDetail> Tbl_TRS_DeliveryOrderDetail { get; set; }
        public virtual Tbl_TRS_StockFG Tbl_TRS_StockFG { get; set; }
        public virtual Tbl_MST_Customer Tbl_MST_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_KanbanProduction> Tbl_MST_KanbanProduction { get; set; }
    }
}
