//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ReceivingOrderDetailKanbanTemp
    {
        public string ReceiveNumber { get; set; }
        public string OrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string KanbanKey { get; set; }
        public string UniqueNumber { get; set; }
        public Nullable<double> ReceiveUnitQty { get; set; }
        public Nullable<System.DateTime> ScanTime { get; set; }
    }
}
