//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_Supplier()
        {
            this.Tbl_MST_SupplierContact = new HashSet<Tbl_MST_SupplierContact>();
            this.Tbl_MST_KanbanCycle = new HashSet<Tbl_MST_KanbanCycle>();
            this.Tbl_MST_SupplierCostCenter = new HashSet<Tbl_MST_SupplierCostCenter>();
            this.Tbl_MST_SupplierBankAccount = new HashSet<Tbl_MST_SupplierBankAccount>();
            this.Tbl_MST_PartRawMaterials = new HashSet<Tbl_MST_PartRawMaterials>();
            this.Tbl_TRS_ReturnPart = new HashSet<Tbl_TRS_ReturnPart>();
        }
    
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Provience { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Websites { get; set; }
        public string TaxId { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_SupplierContact> Tbl_MST_SupplierContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_KanbanCycle> Tbl_MST_KanbanCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_SupplierCostCenter> Tbl_MST_SupplierCostCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_SupplierBankAccount> Tbl_MST_SupplierBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartRawMaterials> Tbl_MST_PartRawMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ReturnPart> Tbl_TRS_ReturnPart { get; set; }
    }
}
