//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TRS_SalesOrder()
        {
            this.Tbl_TRS_SalesOrderDetail = new HashSet<Tbl_TRS_SalesOrderDetail>();
            this.Tbl_TRS_DeliveryOrder = new HashSet<Tbl_TRS_DeliveryOrder>();
        }
    
        public string SONumber { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public string CustomerId { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string DeliveryMonth { get; set; }
        public string DeliveryYear { get; set; }
        public Nullable<bool> PassThrough { get; set; }
        public Nullable<double> StartDelivery { get; set; }
        public Nullable<System.DateTime> StartDateDelivery { get; set; }
        public Nullable<System.DateTime> EndDateDelivery { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_SalesOrderDetail> Tbl_TRS_SalesOrderDetail { get; set; }
        public virtual Tbl_MST_Customer Tbl_MST_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_DeliveryOrder> Tbl_TRS_DeliveryOrder { get; set; }
    }
}
