//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ScheduleDelivery
    {
        public string SONumber { get; set; }
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<double> DeliveryQty { get; set; }
    
        public virtual Tbl_TRS_SalesOrderDetail Tbl_TRS_SalesOrderDetail { get; set; }
    }
}
