//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_KanbanProduction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_KanbanProduction()
        {
            this.Tbl_TRS_ProductionLineProcess = new HashSet<Tbl_TRS_ProductionLineProcess>();
        }
    
        public string KanbanKey { get; set; }
        public string LineId { get; set; }
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> KanbanRun { get; set; }
        public Nullable<bool> ScanIn { get; set; }
        public Nullable<bool> ScanOut { get; set; }
        public Nullable<bool> Storage { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_Line Tbl_MST_Line { get; set; }
        public virtual Tbl_MST_PartFinishGoods Tbl_MST_PartFinishGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ProductionLineProcess> Tbl_TRS_ProductionLineProcess { get; set; }
    }
}
