//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ACC_CustomerInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ACC_CustomerInvoice()
        {
            this.Tbl_ACC_CustomerInvoiceApproval = new HashSet<Tbl_ACC_CustomerInvoiceApproval>();
            this.Tbl_ACC_CustomerInvoiceDetail = new HashSet<Tbl_ACC_CustomerInvoiceDetail>();
        }
    
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CustomerId { get; set; }
        public Nullable<System.DateTime> DOStart { get; set; }
        public Nullable<System.DateTime> DOEnd { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> PPN { get; set; }
        public Nullable<double> PPH23 { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public string Terms { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IncludePPH23 { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ACC_CustomerInvoiceApproval> Tbl_ACC_CustomerInvoiceApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ACC_CustomerInvoiceDetail> Tbl_ACC_CustomerInvoiceDetail { get; set; }
        public virtual Tbl_ACC_CustomerInvoiceReceivable Tbl_ACC_CustomerInvoiceReceivable { get; set; }
    }
}
