//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_QC_ProblemInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_QC_ProblemInformation()
        {
            this.Tbl_QC_ProblemInformationApproval = new HashSet<Tbl_QC_ProblemInformationApproval>();
        }
    
        public string ProblemNumber { get; set; }
        public Nullable<System.DateTime> ProblemDate { get; set; }
        public Nullable<System.DateTime> ProblemTime { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<System.DateTime> ClosingTime { get; set; }
        public string InspectionGate { get; set; }
        public string ProblemInformation { get; set; }
        public string FollowUp { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_InspectionGate Tbl_MST_InspectionGate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_QC_ProblemInformationApproval> Tbl_QC_ProblemInformationApproval { get; set; }
    }
}
