//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_PartRawMaterials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MST_PartRawMaterials()
        {
            this.Tbl_MST_PartFinishGoodsRelation = new HashSet<Tbl_MST_PartFinishGoodsRelation>();
            this.Tbl_MST_PartRawMaterialsCostCenter = new HashSet<Tbl_MST_PartRawMaterialsCostCenter>();
            this.Tbl_MST_PartRawMaterialsPrice = new HashSet<Tbl_MST_PartRawMaterialsPrice>();
            this.Tbl_TRS_StockWIP = new HashSet<Tbl_TRS_StockWIP>();
            this.Tbl_TRS_ReturnPartDetail = new HashSet<Tbl_TRS_ReturnPartDetail>();
        }
    
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public string PartNumberSupplier { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public string PartModel { get; set; }
        public string CategoryId { get; set; }
        public string PackingId { get; set; }
        public string AreaId { get; set; }
        public string LocationId { get; set; }
        public string UnitLevel1 { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public Nullable<double> SafetyHours { get; set; }
        public string SSP { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Tbl_MST_MeasurementsCategories Tbl_MST_MeasurementsCategories { get; set; }
        public virtual Tbl_MST_MeasurementsPacking Tbl_MST_MeasurementsPacking { get; set; }
        public virtual Tbl_MST_MeasurementsUnits Tbl_MST_MeasurementsUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartFinishGoodsRelation> Tbl_MST_PartFinishGoodsRelation { get; set; }
        public virtual Tbl_MST_Supplier Tbl_MST_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartRawMaterialsCostCenter> Tbl_MST_PartRawMaterialsCostCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MST_PartRawMaterialsPrice> Tbl_MST_PartRawMaterialsPrice { get; set; }
        public virtual Tbl_TRS_Stock Tbl_TRS_Stock { get; set; }
        public virtual Tbl_TRS_StockSSP Tbl_TRS_StockSSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_StockWIP> Tbl_TRS_StockWIP { get; set; }
        public virtual Tbl_TRS_StockRawReturn Tbl_TRS_StockRawReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TRS_ReturnPartDetail> Tbl_TRS_ReturnPartDetail { get; set; }
    }
}
