//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MST_LineGate
    {
        public string LineId { get; set; }
        public string GateId { get; set; }
        public string GateName { get; set; }
    
        public virtual Tbl_MST_Line Tbl_MST_Line { get; set; }
    }
}
