//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TRS_ForecastOrderDetail
    {
        public string OrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> OrderLastQty { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> DailyQty { get; set; }
        public Nullable<double> DailyLastQty { get; set; }
        public Nullable<double> N1 { get; set; }
        public Nullable<double> N2 { get; set; }
        public Nullable<double> N3 { get; set; }
        public Nullable<double> FluctuationQty { get; set; }
        public Nullable<double> FluctuationPercent { get; set; }
        public string SONumber { get; set; }
    
        public virtual Tbl_TRS_ForecastOrder Tbl_TRS_ForecastOrder { get; set; }
    }
}
