//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ACC_CustomerInvoiceReceivableYearly
    {
        public Nullable<long> Years { get; set; }
        public string CustomerId { get; set; }
        public string AccountCode { get; set; }
        public string CustomerName { get; set; }
        public double JAN { get; set; }
        public double FEB { get; set; }
        public double MAR { get; set; }
        public double APR { get; set; }
        public double MAY { get; set; }
        public double JUN { get; set; }
        public double JUL { get; set; }
        public double AUG { get; set; }
        public double SEP { get; set; }
        public double OCT { get; set; }
        public double NOV { get; set; }
        public double DEC { get; set; }
        public double TOTAL { get; set; }
    }
}
