//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ACC_CustomerInvoiceDeliveryRecap
    {
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string SONumber { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string RefNumber { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<double> DeliveryUnitQty { get; set; }
        public string UnitLevel2 { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<bool> Invoiced { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
    }
}
