//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ACC_CustomerInvoiceDetail
    {
        public string InvoiceNumber { get; set; }
        public string CustomerId { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<double> PriceUnit { get; set; }
        public Nullable<double> InvoiceQty { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
