//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ACC_InvoiceRecap
    {
        public string RecapNumber { get; set; }
        public Nullable<System.DateTime> RecapDate { get; set; }
        public string RecapYear { get; set; }
        public string RecapMonth { get; set; }
        public string InvoiceNumber { get; set; }
        public string ReceiveNote { get; set; }
        public string TaxInvoice { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<double> PPN { get; set; }
        public Nullable<double> PPH23 { get; set; }
        public Nullable<double> DebitNote { get; set; }
        public Nullable<int> TotalPart { get; set; }
        public Nullable<double> TotalRecap { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Approval { get; set; }
        public Nullable<int> ApprovalLevel { get; set; }
        public string ApprovalName { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<System.DateTime> ReceiveStartDate { get; set; }
        public Nullable<System.DateTime> ReceiveEndDate { get; set; }
    }
}
