//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_IDX_StockTakingEvent
    {
        public string InventoryNumber { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public Nullable<System.DateTime> InventoryStartTime { get; set; }
        public Nullable<System.DateTime> InventoryEndTime { get; set; }
        public string InventoryStatus { get; set; }
    }
}
