//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_IDX_StockListSummary
    {
        public string StockType { get; set; }
        public Nullable<int> TotalItem { get; set; }
        public Nullable<int> TotalOver { get; set; }
        public Nullable<int> TotalMinus { get; set; }
        public Nullable<double> PercentOver { get; set; }
        public Nullable<double> PercentMinus { get; set; }
    }
}
