//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MST_PartRawMaterialsPriceMonthly
    {
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string PartModel { get; set; }
        public string Years { get; set; }
        public Nullable<double> JAN { get; set; }
        public Nullable<double> FEB { get; set; }
        public Nullable<double> MAR { get; set; }
        public Nullable<double> APR { get; set; }
        public Nullable<double> MAY { get; set; }
        public Nullable<double> JUN { get; set; }
        public Nullable<double> JUL { get; set; }
        public Nullable<double> AUG { get; set; }
        public Nullable<double> SEP { get; set; }
        public Nullable<double> OCT { get; set; }
        public Nullable<double> NOV { get; set; }
        public Nullable<double> DEC { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
