//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MST_Customer
    {
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Provience { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Websites { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string TaxId { get; set; }
        public string CustomerCode { get; set; }
        public string AccountCode { get; set; }
    }
}
