//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MST_BillOfMaterialsDetails
    {
        public string CustomerId { get; set; }
        public string LineId { get; set; }
        public string BOMNumber { get; set; }
        public Nullable<int> BOMLevel { get; set; }
        public Nullable<bool> Level01 { get; set; }
        public Nullable<bool> Level02 { get; set; }
        public Nullable<bool> Level03 { get; set; }
        public Nullable<bool> Level04 { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string Revision { get; set; }
        public string LevelName { get; set; }
        public Nullable<double> CostUnit { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Passthrough { get; set; }
    }
}
