//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MST_PartFinishGoodsRelation
    {
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumberRawMaterial { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> QtyUsage { get; set; }
        public string SSP { get; set; }
        public string ProcessName { get; set; }
        public Nullable<bool> SSPStock { get; set; }
        public Nullable<bool> DeliveryOrder { get; set; }
        public Nullable<bool> DeliveryRawMaterial { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
