//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_QC_InspectionIncoming
    {
        public string Years { get; set; }
        public string Months { get; set; }
        public string InspectionNumber { get; set; }
        public string InspectionGate { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public string UniqueNumber { get; set; }
        public string SupplierUniqueNumber { get; set; }
        public string PartName { get; set; }
        public string PartModel { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string PartCategory { get; set; }
        public string PI_Images { get; set; }
        public Nullable<double> TotalCheck { get; set; }
        public Nullable<double> TotalDefectUnit { get; set; }
        public Nullable<double> TotalDefectQty { get; set; }
        public Nullable<double> Replaced { get; set; }
        public Nullable<double> Remains { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
