//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_QC_ProblemInformation
    {
        public string ProblemNumber { get; set; }
        public Nullable<System.DateTime> ProblemDate { get; set; }
        public Nullable<System.DateTime> ProblemTime { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<System.DateTime> ClosingTime { get; set; }
        public string InspectionType { get; set; }
        public string InspectionGate { get; set; }
        public string GateName { get; set; }
        public string ProblemInformation { get; set; }
        public string FollowUp { get; set; }
        public string NotificationTo { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
