//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_QC_InspectionIncomingDefects
    {
        public string Years { get; set; }
        public string Months { get; set; }
        public string InspectionNumber { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string InspectionGate { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public string UniqueNumber { get; set; }
        public string SupplierUniqueNumber { get; set; }
        public string PartName { get; set; }
        public string PartModel { get; set; }
        public string DefectId { get; set; }
        public string DefectName { get; set; }
        public string DefectCategory { get; set; }
        public string DefectCategoryName { get; set; }
        public string PartCategory { get; set; }
        public string PartCategoryName { get; set; }
        public Nullable<double> DefectQty { get; set; }
        public Nullable<bool> PartReturn { get; set; }
        public Nullable<bool> Repair { get; set; }
        public Nullable<bool> Scrap { get; set; }
    }
}
