//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_SYS_SchemaColumnList
    {
        public string SCHEMA_NAMES { get; set; }
        public string COLUMNNAME { get; set; }
        public Nullable<int> POSITION { get; set; }
        public string IS_NULLABLE { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<int> LENGHT { get; set; }
    }
}
