//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_SalesOrder
    {
        public string SONumber { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<bool> PassThrough { get; set; }
        public string DeliveryYear { get; set; }
        public string DeliveryMonth { get; set; }
        public Nullable<int> TotalPart { get; set; }
        public Nullable<double> TotalOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<double> StartDelivery { get; set; }
        public Nullable<System.DateTime> StartDateDelivery { get; set; }
        public Nullable<System.DateTime> EndDateDelivery { get; set; }
    }
}
