//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_SalesOrderOutstanding
    {
        public string DeliveryYear { get; set; }
        public string DeliveryMonth { get; set; }
        public string SONumber { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public string CustomerId { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartNumberCustomer { get; set; }
        public string PartName { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<double> OrderKanban { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public double DeliveryKanban { get; set; }
        public double DeliveryQty { get; set; }
        public Nullable<double> OutstandingKanban { get; set; }
        public Nullable<double> OutstandingQty { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
