//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_StockAdjustmentDetail
    {
        public string AdjustmentNumber { get; set; }
        public string SupplierId { get; set; }
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public string AreaId { get; set; }
        public string LocationId { get; set; }
        public string CategoryId { get; set; }
        public string PartModel { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string UnitLevel2 { get; set; }
        public string PackingId { get; set; }
        public Nullable<double> StockKanban { get; set; }
        public Nullable<double> StockQty { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BalanceQty { get; set; }
        public Nullable<double> AdjustmentQty { get; set; }
        public string LineId { get; set; }
    }
}
