//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_ReportDeliveryOrder
    {
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string DeliveryYear { get; set; }
        public string DeliveryMonth { get; set; }
        public string MonthNames { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PartNumber { get; set; }
        public string PartNumberCustomer { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<bool> PassThrough { get; set; }
        public string UnitLevel2 { get; set; }
        public double PriceUnit { get; set; }
        public Nullable<double> DeliveryQty { get; set; }
        public Nullable<double> PriceTotal { get; set; }
        public Nullable<int> Status { get; set; }
        public string RefNumber { get; set; }
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}
