//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_SupplierOrderDetail
    {
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> MaxStock { get; set; }
        public Nullable<double> StockKanban { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> OrderUnitQty { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
        public Nullable<double> OutstandingQty { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> IncomingDate { get; set; }
        public Nullable<System.DateTime> IncomingTime { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public string PartModel { get; set; }
        public string UnitLevel2 { get; set; }
    }
}
