//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_DeliveryOrder
    {
        public string DOYear { get; set; }
        public string DOMonth { get; set; }
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string DeliveryAddress { get; set; }
        public string SONumber { get; set; }
        public string PONumber { get; set; }
        public string RefNumber { get; set; }
        public int TotalItem { get; set; }
        public int TotalDelivery { get; set; }
        public string Remarks { get; set; }
        public bool KanbanOrder { get; set; }
        public string KanbanUsage { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
