//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_StockRawReturn
    {
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string City { get; set; }
        public string CostId { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string AreaId { get; set; }
        public string LocationId { get; set; }
        public string CategoryId { get; set; }
        public string PartModel { get; set; }
        public string PackingId { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string UnitLevel1 { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<double> MinStock { get; set; }
        public Nullable<double> MaxStock { get; set; }
        public Nullable<double> StockQty { get; set; }
        public double OutstandingQty { get; set; }
        public Nullable<double> TotalStockQty { get; set; }
        public Nullable<double> PriceUnit { get; set; }
        public Nullable<double> PriceTotalStock { get; set; }
        public Nullable<double> PriceTotalOutstanding { get; set; }
        public Nullable<double> PriceTotal { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
