//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_RequestOrderPartCreateList
    {
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public string ShiftId { get; set; }
        public string LineId { get; set; }
        public string SupplierId { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string UnitLevel1 { get; set; }
        public string UnitLevel2 { get; set; }
        public string PackingId { get; set; }
        public string PartModel { get; set; }
        public Nullable<double> MaxStock { get; set; }
        public Nullable<double> ProductionQty { get; set; }
        public Nullable<double> UsageQty { get; set; }
        public double StockKanban { get; set; }
        public double StockQty { get; set; }
        public Nullable<double> OrderKanbanQty { get; set; }
        public Nullable<double> OrderUnitQty { get; set; }
    }
}
