//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_ReportDeliveryOrderSummary
    {
        public string Years { get; set; }
        public string MonthString { get; set; }
        public string MonthNames { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> TotalItem { get; set; }
        public double TotalDelivery { get; set; }
        public double TotalPrice { get; set; }
    }
}
