//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_DeliveryOrderRelation
    {
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string CustomerId { get; set; }
        public string PartNumber { get; set; }
        public string SupplierId { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumberRawMaterial { get; set; }
        public Nullable<double> DeliveryQty { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public Nullable<double> KanbanQty { get; set; }
    }
}
