//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_ReceivingOrderDetail
    {
        public string ReceiveNumber { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> Schedule { get; set; }
        public Nullable<int> DiffTime { get; set; }
        public string OrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string UnitLevel1 { get; set; }
        public string UnitLevel2 { get; set; }
        public string PackingId { get; set; }
        public string PartModel { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> OrderUnitQty { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
        public Nullable<double> ReceiveUnitQty { get; set; }
        public Nullable<double> OutstandingQty { get; set; }
        public Nullable<double> OutstandingUnitQty { get; set; }
        public string RecapNumber { get; set; }
        public Nullable<bool> ReturnPart { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
