//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_ScheduleProduction
    {
        public string OrderNumber { get; set; }
        public string LineId { get; set; }
        public string LineName { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string City { get; set; }
        public string PartNumber { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public Nullable<double> ProductionPerDay { get; set; }
        public Nullable<double> ProductionPerShift { get; set; }
        public string ShiftId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<double> ProductionQty { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
