//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_SalesDeliveryStatus
    {
        public string SONumber { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public string CustomerId { get; set; }
        public Nullable<double> DeliveryUnitQty { get; set; }
        public Nullable<double> SalesUnitQty { get; set; }
        public Nullable<double> Balance { get; set; }
        public int Status { get; set; }
    }
}
