//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_StockControlDaily
    {
        public string OrderYear { get; set; }
        public string OrderMonth { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string PartNumber { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public string PartModel { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> DailyQty { get; set; }
        public double EarlyStock { get; set; }
        public Nullable<double> C_01_StockIn { get; set; }
        public Nullable<double> C_01_StockOut { get; set; }
        public Nullable<double> C_02_StockIn { get; set; }
        public Nullable<double> C_02_StockOut { get; set; }
        public Nullable<double> C_03_StockIn { get; set; }
        public Nullable<double> C_03_StockOut { get; set; }
        public Nullable<double> C_04_StockIn { get; set; }
        public Nullable<double> C_04_StockOut { get; set; }
        public Nullable<double> C_05_StockIn { get; set; }
        public Nullable<double> C_05_StockOut { get; set; }
        public Nullable<double> C_06_StockIn { get; set; }
        public Nullable<double> C_06_StockOut { get; set; }
        public Nullable<double> C_07_StockIn { get; set; }
        public Nullable<double> C_07_StockOut { get; set; }
        public Nullable<double> C_08_StockIn { get; set; }
        public Nullable<double> C_08_StockOut { get; set; }
        public Nullable<double> C_09_StockIn { get; set; }
        public Nullable<double> C_09_StockOut { get; set; }
        public Nullable<double> C_10_StockIn { get; set; }
        public Nullable<double> C_10_StockOut { get; set; }
        public Nullable<double> C_11_StockIn { get; set; }
        public Nullable<double> C_11_StockOut { get; set; }
        public Nullable<double> C_12_StockIn { get; set; }
        public Nullable<double> C_12_StockOut { get; set; }
        public Nullable<double> C_13_StockIn { get; set; }
        public Nullable<double> C_13_StockOut { get; set; }
        public Nullable<double> C_14_StockIn { get; set; }
        public Nullable<double> C_14_StockOut { get; set; }
        public Nullable<double> C_15_StockIn { get; set; }
        public Nullable<double> C_15_StockOut { get; set; }
        public Nullable<double> C_16_StockIn { get; set; }
        public Nullable<double> C_16_StockOut { get; set; }
        public Nullable<double> C_17_StockIn { get; set; }
        public Nullable<double> C_17_StockOut { get; set; }
        public Nullable<double> C_18_StockIn { get; set; }
        public Nullable<double> C_18_StockOut { get; set; }
        public Nullable<double> C_19_StockIn { get; set; }
        public Nullable<double> C_19_StockOut { get; set; }
        public Nullable<double> C_20_StockIn { get; set; }
        public Nullable<double> C_20_StockOut { get; set; }
        public Nullable<double> C_21_StockIn { get; set; }
        public Nullable<double> C_21_StockOut { get; set; }
        public Nullable<double> C_22_StockIn { get; set; }
        public Nullable<double> C_22_StockOut { get; set; }
        public Nullable<double> C_23_StockIn { get; set; }
        public Nullable<double> C_23_StockOut { get; set; }
        public Nullable<double> C_24_StockIn { get; set; }
        public Nullable<double> C_24_StockOut { get; set; }
        public Nullable<double> C_25_StockIn { get; set; }
        public Nullable<double> C_25_StockOut { get; set; }
        public Nullable<double> C_26_StockIn { get; set; }
        public Nullable<double> C_26_StockOut { get; set; }
        public Nullable<double> C_27_StockIn { get; set; }
        public Nullable<double> C_27_StockOut { get; set; }
        public Nullable<double> C_28_StockIn { get; set; }
        public Nullable<double> C_28_StockOut { get; set; }
        public Nullable<double> C_29_StockIn { get; set; }
        public Nullable<double> C_29_StockOut { get; set; }
        public Nullable<double> C_30_StockIn { get; set; }
        public Nullable<double> C_30_StockOut { get; set; }
        public Nullable<double> C_31_StockIn { get; set; }
        public Nullable<double> C_31_StockOut { get; set; }
    }
}
