//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_ForecastAchievement
    {
        public string OrderYear { get; set; }
        public string OrderMonth { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string PartNumber { get; set; }
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public string PartModel { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public double ReceivedQty { get; set; }
        public Nullable<double> BalanceQty { get; set; }
        public Nullable<double> BalancePercent { get; set; }
    }
}
