//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_ProductionLineProcess
    {
        public string ProductionYear { get; set; }
        public string ProductionMonth { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string ShiftId { get; set; }
        public string LineId { get; set; }
        public string LineName { get; set; }
        public string GateId { get; set; }
        public string GateName { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string PackingId { get; set; }
        public Nullable<int> TotalKanban { get; set; }
        public Nullable<double> TotalQtyOK { get; set; }
        public Nullable<double> TotalQtyNG { get; set; }
        public string UnitLevel2 { get; set; }
        public string OrderNumber { get; set; }
        public string UserId { get; set; }
    }
}
