//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TMS_ShiftGroup
    {
        public string GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> TotalShift { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<double> WorkHour { get; set; }
    }
}
