//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_StockFG
    {
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string City { get; set; }
        public string SupplierId { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string AreaId { get; set; }
        public string LocationId { get; set; }
        public string CategoryId { get; set; }
        public string CustomerUnitModel { get; set; }
        public string PackingId { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string UnitLevel1 { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<bool> PassThrough { get; set; }
        public double MinStock { get; set; }
        public double MaxStock { get; set; }
        public double StockKanban { get; set; }
        public double StockQty { get; set; }
        public double EarlyStockQty { get; set; }
        public Nullable<double> PriceUnit { get; set; }
        public Nullable<double> PriceStock { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
