//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_DeliveryOrderKanbanSumTemp
    {
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string SONumber { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartNumberCustomer { get; set; }
        public string PartName { get; set; }
        public Nullable<bool> PassThrough { get; set; }
        public string CustomerUnitModel { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string UnitLevel1 { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<int> DeliveryQty { get; set; }
        public Nullable<double> DeliveryUnitQty { get; set; }
    }
}
