//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_StockFinanceReport
    {
        public string UniqueNumber { get; set; }
        public string PartName { get; set; }
        public string PartNumber { get; set; }
        public string StockType { get; set; }
        public string UnitLevel2 { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string PartModel { get; set; }
        public double EarlyStockQty { get; set; }
        public Nullable<double> StockIn { get; set; }
        public Nullable<double> StockOut { get; set; }
        public Nullable<double> StockBalance { get; set; }
        public Nullable<double> InStockQty { get; set; }
        public Nullable<double> AbnormalQty { get; set; }
        public double Price { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string AreaId { get; set; }
        public string AreaName { get; set; }
        public string LocationId { get; set; }
        public string LocationName { get; set; }
    }
}
