//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_ReceivingOrderDetailTemp
    {
        public string ReceiveNumber { get; set; }
        public string OrderNumber { get; set; }
        public string SupplierId { get; set; }
        public string UniqueNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<double> UnitQty { get; set; }
        public string Unit { get; set; }
        public string PackingId { get; set; }
        public string PartModel { get; set; }
        public Nullable<double> OrderQty { get; set; }
        public Nullable<double> OrderUnitQty { get; set; }
        public Nullable<int> ReceiveQty { get; set; }
        public Nullable<double> ReceiveUnitQty { get; set; }
        public Nullable<double> OutstandingQty { get; set; }
        public Nullable<double> OutstandingUnitQty { get; set; }
    }
}
