//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.VSSP.WorkEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TRS_StockTaking
    {
        public string InventoryYear { get; set; }
        public string InventoryMonth { get; set; }
        public string InventoryNumber { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public Nullable<System.DateTime> InventoryStartTime { get; set; }
        public Nullable<System.DateTime> InventoryEndTime { get; set; }
        public string StockType { get; set; }
        public Nullable<int> TotalPart { get; set; }
        public Nullable<double> TotalOrder { get; set; }
        public Nullable<bool> Updated { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public string Approval { get; set; }
        public Nullable<int> ApprovalLevel { get; set; }
        public string ApprovalName { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string InventoryKey { get; set; }
    }
}
